name: CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run tests
        run: |
          docker-compose exec -T your_service_name sh -c "npm test"
          # or replace `npm test` with your actual test command

      - name: Tear down
        if: always()
        run: docker-compose down --volumes
